spring:

  mvc:

   pathmatch:

    matching-strategy: ant_path_matcher


  datasource:

    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    # jdbc:mysql://{ip번호}:{포트번호}/{dataBase}? ...
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: #userId
    password: #password

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

logging:
  level:
    com.tutorial: debug

jwt:
  secret: #보안키 값

