spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: oauth, secret

  datasource:
    url: ${{ secrets.DATASOURCE_URL }}
    username: ${{ secrets.DATASOURCE_NAME }}
    password: ${{ secrets.DATASOURCE_PASSWORD }}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

ip: db
